baseURL = "https://x-talks.github.io/x/"
locale = "en-US"
title = "Master Blog"

[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"

[params]
  description = "Master Blog — daily observations, podcast, video"
